#
# Github Action to setup The SELinux Notebook build
#
# Copyright (c) 2022 Microsoft Corporation <paulmoore@microsoft.com>
# Author: Paul Moore <paul@paul-moore.com>
#

name: Setup the build for The SELinux Notebook
description: "Install dependencies for The SELinux Notebook build"
runs:
  using: "composite"
  steps:
  - run: sudo apt-get update
    shell: bash
  - run: sudo apt-get install -y build-essential weasyprint pandoc calibre
    shell: bash
